Numpy lib

In [1]:
import numpy as np

In [4]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [9]:
#array com 2 dimensões
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [16]:
c = np.eye(5)
print(c)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [17]:
b.std()

1.707825127659933