Pandas lib

In [1]:
import pandas as pd

In [2]:
dados = pd.read_excel('arquivo1.xlsx')

In [3]:
dados.head(6)

Números Letras
0        1      a
1        2      b
2        3      c
3        4      d
4        5      e
5        6      f

In [6]:
alunos = {
    'Nome': ['Ricardo','Pedro','Roberto','João'],
    'Nota': [10, 6, 3, 8.5], 
    'Aprovado': ['Sim','Sim','Não','Sim']
}

In [19]:
alunosDF = pd.DataFrame(alunos)
alunosDF

Nome  Nota Aprovado
0  Ricardo  10.0      Sim
1    Pedro   6.0      Sim
2  Roberto   3.0      Não
3     João   8.5      Sim

In [8]:
objeto1 = pd.Series([2,6,9,10,7])
objeto1

0     2
1     6
2     9
3    10
4     7
dtype: int64

In [ ]:
#Diferença entre array e series
import numpy as np
array1 = np.array([2,6,9,10,7])
array2 = np.array([[2,6,9,10,5],[6,12,2,9,10]])
print('array\n',array1)
print('=========')
print('series\n',objeto1)

array
 [ 2  6  9 10  7]
series
 0     2
1     6
2     9
3    10
4     7
dtype: int64


In [16]:
array1 = np.array([2,6,9,10,7])
array2 = np.array([[2,6,9,10,5],[6,12,2,9,10]])
print('array unidimensional\n',array1)
print('=======')
print('array bidimensional\n',array2)

array unidimensional
 [ 2  6  9 10  7]
array bidimensional
 [[ 2  6  9 10  5]
 [ 6 12  2  9 10]]


In [ ]:
objeto2 = pd.Series(array2)
print(objeto2)
#erro itencional
#não funciona com array bidimensional

ValueError: Data must be 1-dimensional, got ndarray of shape (2, 5) instead

In [20]:
alunosDF.head()

Nome  Nota Aprovado
0  Ricardo  10.0      Sim
1    Pedro   6.0      Sim
2  Roberto   3.0      Não
3     João   8.5      Sim

In [ ]:
#Número de linhas e número de colunas
alunosDF.shape

(4, 3)

In [23]:
alunosDF.describe()

Nota
count   4.000000
mean    6.875000
std     3.065262
min     3.000000
25%     5.250000
50%     7.250000
75%     8.875000
max    10.000000

In [ ]:
#filtrando colunas
alunosDF['Aprovado']

0    Sim
1    Sim
2    Não
3    Sim
Name: Aprovado, dtype: object

In [ ]:
#filtrando linhas
alunosDF.loc[[0]]

Nome  Nota Aprovado
0  Ricardo  10.0      Sim

In [31]:
alunosDF.loc[0:2]

Nome  Nota Aprovado
0  Ricardo  10.0      Sim
1    Pedro   6.0      Sim
2  Roberto   3.0      Não

In [34]:
#quais dados são iguais a Pedro dentro da coluna Nome que pertence ao dataframe AlunosDF
alunosDF.loc[alunosDF['Nome']=='Pedro']

Nome  Nota Aprovado
1  Pedro   6.0      Sim

In [36]:
alunosDF2 = alunosDF.loc[0:2]
alunosDF2

Nome  Nota Aprovado
0  Ricardo  10.0      Sim
1    Pedro   6.0      Sim
2  Roberto   3.0      Não

In [41]:
novoDF = alunosDF.loc[alunosDF['Nota'] != 3]
novoDF

Nome  Nota Aprovado
0  Ricardo  10.0      Sim
1    Pedro   6.0      Sim
3     João   8.5      Sim

In [43]:
alunosReprovados = alunosDF.loc[alunosDF['Aprovado'] == 'Não']
alunosReprovados

Nome  Nota Aprovado
2  Roberto   3.0      Não

In [45]:
atletas = pd.read_csv('athlete_events.csv')
atletas.head()

ID                      Name Sex   Age  Height  Weight            Team  \
0   1                 A Dijiang   M  24.0   180.0    80.0           China   
1   2                  A Lamusi   M  23.0   170.0    60.0           China   
2   3       Gunnar Nielsen Aaby   M  24.0     NaN     NaN         Denmark   
3   4      Edgar Lindenau Aabye   M  34.0     NaN     NaN  Denmark/Sweden   
4   5  Christine Jacoba Aaftink   F  21.0   185.0    82.0     Netherlands   

   NOC        Games  Year  Season       City          Sport  \
0  CHN  1992 Summer  1992  Summer  Barcelona     Basketball   
1  CHN  2012 Summer  2012  Summer     London           Judo   
2  DEN  1920 Summer  1920  Summer  Antwerpen       Football   
3  DEN  1900 Summer  1900  Summer      Paris     Tug-Of-War   
4  NED  1988 Winter  1988  Winter    Calgary  Speed Skating   

                              Event Medal  
0       Basketball Men's Basketball   NaN  
1      Judo Men's Extra-Lightweight   NaN  
2           Football Men's Football   NaN  
3       Tug-Of-War Men's Tug-Of-War  Gold  
4  Speed Skating Women's 500 metres   NaN

In [ ]:
#inplace não exibe o resultado final 
atletas.rename(columns={'Name':'Nome','Sex':'Gênero','Age':'Idade'}, inplace=True)

In [ ]:
atletas['Height']
altura = atletas['Height']

pandas.core.series.Series

In [ ]:
#Quando se atribui apenas uma coluna, a variável automaticamente se torna uma Series
type(altura)

pandas.core.series.Series

In [53]:
#Quantas vezes cada valor único aparece
atletas['City'].value_counts()

City
London                    22426
Athina                    15556
Sydney                    13821
Atlanta                   13780
Rio de Janeiro            13688
Beijing                   13602
Barcelona                 12977
Los Angeles               12423
Seoul                     12037
Munich                    10304
Montreal                   8641
Mexico City                8588
Helsinki                   8270
Roma                       8119
Tokyo                      7702
Moskva                     7191
Paris                      7169
Berlin                     6506
Amsterdam                  4992
Sochi                      4891
Melbourne                  4829
Vancouver                  4402
Torino                     4382
Stockholm                  4338
Antwerpen                  4292
Salt Lake City             4109
Innsbruck                  3639
Nagano                     3605
Albertville                3436
Lillehammer                3160
Calgary                    2639
Sar

In [54]:
#axis=1 coluna/ axis=0 linha
atletas.drop('ID', axis=1, inplace=True)
atletas.drop('Season', axis=1, inplace=True)
atletas.drop('City', axis=1, inplace=True)

In [55]:
atletas.head()

Nome Gênero  Idade  Height  Weight            Team  \
0                 A Dijiang      M   24.0   180.0    80.0           China   
1                  A Lamusi      M   23.0   170.0    60.0           China   
2       Gunnar Nielsen Aaby      M   24.0     NaN     NaN         Denmark   
3      Edgar Lindenau Aabye      M   34.0     NaN     NaN  Denmark/Sweden   
4  Christine Jacoba Aaftink      F   21.0   185.0    82.0     Netherlands   

   NOC        Games  Year          Sport                             Event  \
0  CHN  1992 Summer  1992     Basketball       Basketball Men's Basketball   
1  CHN  2012 Summer  2012           Judo      Judo Men's Extra-Lightweight   
2  DEN  1920 Summer  1920       Football           Football Men's Football   
3  DEN  1900 Summer  1900     Tug-Of-War       Tug-Of-War Men's Tug-Of-War   
4  NED  1988 Winter  1988  Speed Skating  Speed Skating Women's 500 metres   

  Medal  
0   NaN  
1   NaN  
2   NaN  
3  Gold  
4   NaN